# SwiftLint Configuration for FlexingUSB

# Disable rules that are too strict for this project
disabled_rules:
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - trailing_whitespace
  - identifier_name

# Paths to include/exclude
included:
  - Sources

excluded:
  - .build
  - release
  - Tests

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_comments: true

function_body_length:
  warning: 100
  error: 200

type_body_length:
  warning: 300
  error: 500

# Reporter type
reporter: "xcode"
